Adds instructions for building iOS from Windows
dotnet/net6-mobile-samples pull request #60
Opened 2021-02-12 21:39 UTC by emaf

iOS workloads need to be updated to include the version with Windows support.

2021-02-12 21:54 UTC, rolfbjarne approved these changes

2021-02-12 22:14 UTC, jonathanpeppers reviewed
Can you link to a commit that has the builds I'd need? I'd like to try these out, thanks.

2021-02-12 22:48 UTC, emaf commented
@jonathanpeppers this is the PR https://github.com/xamarin/xamarin-macios/pull/10638, the build pipeline is still running but the packages were already produced

2021-02-12 22:53 UTC, jonathanpeppers requested changes
Thanks, I'll try these out: https://github.com/xamarin/xamarin-macios/pull/10638

Since we are likely shipping the packages on the current `README.md` for a Preview 1, let's wait to merge this for a few days.

We should probably update download links at the same time as adding these instructions, though.

2021-02-16 16:07 UTC, Redth approved these changes

2021-02-16 17:47 UTC, rolfbjarne commented
> @rolfbjarne I just updated the links to the iOS workloads, please check if those are correct. Thanks!

I think you have to update here too:

https://github.com/dotnet/net6-mobile-samples/blob/0890331cbc5e41b576f1216a3d5a57634bf170af/azure-pipelines.yml#L14-L15

2021-02-17 20:00 UTC, jonathanpeppers commented on README.md
> +1][net6preview1] for Xcode 12.3:
@Redth I put this note for now. Do we want to wait a little while to merge this?

This literally _just_ came out: https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/

2021-02-17 20:00 UTC, jonathanpeppers approved these changes

2021-02-18 16:33 UTC, jonathanpeppers commented
/azp run

2021-02-18 16:34 UTC, jonathanpeppers commented
/azp run

2021-02-18 16:52 UTC, merged